#!/usr/bin/env node

const yargs = require("yargs")
const Options = require("./options")
const Date = require("./date")
const commit = require("./commit")

const { date, time, days, message } = Options.parse(yargs).argv

commit(
  Date.compute(date, time, days),
  message
)
